Document: piccolo3-common
Title: Debian piccolo3-common Manual
Author: <insert document author here>
Abstract: This manual describes what piccolo3-common is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/piccolo3-common/piccolo3-common.sgml.gz

Format: postscript
Files: /usr/share/doc/piccolo3-common/piccolo3-common.ps.gz

Format: text
Files: /usr/share/doc/piccolo3-common/piccolo3-common.text.gz

Format: HTML
Index: /usr/share/doc/piccolo3-common/html/index.html
Files: /usr/share/doc/piccolo3-common/html/*.html
